// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using T_Service.Data;

namespace TService.Migrations
{
    [DbContext(typeof(T_ServiceContext))]
    [Migration("20180203103436_v1.0.0")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("T_Service.Models.cDelivery_product", b =>
                {
                    b.Property<long>("delivery_product_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_datetime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<bool>("isCancelled");

                    b.Property<string>("nameEN");

                    b.Property<string>("nameTH");

                    b.Property<string>("product_code");

                    b.Property<int>("quantity_number");

                    b.Property<DateTime>("updated_datetime");

                    b.HasKey("delivery_product_id");

                    b.ToTable("DeliveryProducts");
                });

            modelBuilder.Entity("T_Service.Models.cDelivery_work", b =>
                {
                    b.Property<long>("delivery_work_id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Tservice_type_id");

                    b.Property<long>("Tservice_work_id");

                    b.Property<long>("Tservice_work_status_id");

                    b.Property<DateTime>("created_datetime")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<long>("delivery_address_amphur_id");

                    b.Property<string>("delivery_address_details");

                    b.Property<long>("delivery_address_district_id");

                    b.Property<string>("delivery_address_map_google_url");

                    b.Property<string>("delivery_address_map_image_url");

                    b.Property<string>("delivery_address_phone_number");

                    b.Property<string>("delivery_address_place_name");

                    b.Property<long>("delivery_address_province_id");

                    b.Property<string>("delivery_address_receiver_name");

                    b.Property<int>("delivery_address_zip_code");

                    b.Property<DateTime>("delivery_appointed_datetime");

                    b.Property<double>("delivery_distance_kilometre");

                    b.Property<DateTime>("delivery_finished_datetime");

                    b.Property<bool>("isCancelled");

                    b.Property<string>("member_email");

                    b.Property<string>("receipt_number");

                    b.Property<string>("remark_employee");

                    b.Property<string>("remark_member");

                    b.Property<string>("signature_customer_image_url");

                    b.Property<DateTime>("updated_datetime");

                    b.HasKey("delivery_work_id");

                    b.ToTable("DeliveryWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
